import type { Metadata } from 'next';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={sans.className}>
      <body className='max mx-auto flex w-full flex-col'>
        <Header />
        <main className='grow p-10'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
